services:
  nginx:
    ports: !reset []

  frontend-demo:
    image: scipioni-frontend-demo:staging
    build:
      context: .
      dockerfile: infra/docker/frontend-demo/Dockerfile
      args:
        SCIPIONI_API_BASE_URL: https://api-staging.scipioni.brane.it/api/v1
    volumes: !reset []
    ports: !reset []

  admin:
    image: scipioni-admin:staging
    build:
      context: .
      dockerfile: infra/docker/admin/Dockerfile
    environment:
      NUXT_ADMIN_API_BASE: http://nginx/api/admin
      NUXT_PUBLIC_ADMIN_API_BASE: https://api-staging.scipioni.brane.it/api/admin
      NUXT_PUBLIC_ADMIN_APP_NAME: Scipioni Staff Console
    ports: !reset []

  mysql:
    ports: !reset []

  redis:
    ports: !reset []

  adminer:
    profiles: ["local-only"]
    ports: !reset []
