services:
  nginx:
    ports: []

  frontend-demo:
    build:
      context: .
      dockerfile: infra/docker/frontend-demo/Dockerfile
      args:
        SCIPIONI_API_BASE_URL: https://api-staging.scipioni.brane.it/api/v1
    volumes: []
    ports: []

  mysql:
    ports: []

  adminer:
    profiles: ["local-only"]
    ports: []
