services:
  app:
    env_file:
      - backend/.env.production

  queue:
    env_file:
      - backend/.env.production

  nginx:
    volumes:
      - ./backend:/var/www/html
      - ./infra/docker/nginx/production-api.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"

  frontend-demo:
    volumes:
      - ./frontend/app/build/web:/usr/share/nginx/html:ro
      - ./infra/docker/frontend-demo/production.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8090:80"
